title: Phenotype from Genotype
author: Natalie Zelenka
email: natalie.thurlby@bristol.ac.uk
logo: images/thesis_logo_with_text.png
description: >-
  Phenotype from Genotype: combining datasets to make explanatory predictions.

baseurl: ""
url: "http://nataliezelenka.github.io/thesis"
only_build_toc_files: true

bibtex_bibfiles:
  - _bibliography/references.bib

favicon_path: "images/logo/favicon.ico"

execute:
  execute_notebooks: cache
  timeout: -1

sphinx:
  extra_extensions:
    - sphinx_jupyterbook_latex
    - sphinx.ext.autosummary
    - sphinx_multitoc_numbering
#  local_extensions:
#      ontolopy:  '../../../../ontolopy'
  config:
    html_js_files:
      - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js  # makes interactive figs work
    html_favicon: images/favicon.png
    autosummary_generate: True
    html_theme_options:
      use_download_button: false
  latex_elements:
    printindex: ''
