# Deploys the book on the gh-pages branch
name: deploy-book

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch for the book content directory.
  push:
    branches: [ main ]
    paths:
      book/**
      
  pull_request:
    branches: [ main ]
    paths:
      book/**

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "deploy-book"
  deploy-book:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
       # Install dependencies
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt      
      
      - name: Set up R
        uses: r-lib/actions/setup-r@v1
        with:
          r-version: '3.6' # The R version to download (if necessary) and use.    
      - run: Rscript install.R

      # Build the book
      - name: Build the book
        run: |
          jupyter-book build book/

      # Push the book's HTML to github-pages
      - name: GitHub Pages action
        uses: peaceiris/actions-gh-pages@v3.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book/_build/html
